<?php

// This file is auto-generated by https://github.com/ElfSundae/php-cs-fixer-config

use PhpCsFixer\Config;
use PhpCsFixer\Finder;
use PhpCsFixer\Runner\Parallel\ParallelConfigFactory;

$rules = ['{{exported}}'];

$finder = Finder::create()
    ->ignoreDotFiles(true)
    ->ignoreVCS(true)
    ->notName([
        '_ide_helper_actions.php',
        '_ide_helper_models.php',
        '_ide_helper.php',
        '.phpstorm.meta.php',
        '*.blade.php',
    ])
    ->exclude([
        'bootstrap/cache',
        'build',
        'node_modules',
        'storage',
        'third',
        'legacy',
    ]);

return (new Config)
    ->setParallelConfig(ParallelConfigFactory::detect())
    ->setRules($rules)
    ->setFinder($finder)
    ->setRiskyAllowed(true)
    ->setUsingCache(false)
    ->setUnsupportedPhpVersionAllowed(true);
